[[language]]
name = "python"
language-servers = [ "ruff", "basedpyright" ]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.basedpyright.config]
basedpyright.analysis.typeCheckingMode = "standard"
